# Conferir informações da tabela da deGraaff

"the Balmer decrement is defined as the ratio between the total (i.e. broad+narrow) Hα and Hβ line flux, again assuming that emission from an underlying host galaxy is subdominant."

In [1]:
%load_ext autoreload
%autoreload 2

In [ ]:
## importing libraries
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits
from astropy.wcs import WCS
import astropy.units as u
import pandas as pd

In [ ]:
fits.info("deGraaff2025_lrds_withdups_blackbody_eline_fits.fits")

Filename: deGraaff2025_lrds_withdups_blackbody_eline_fits.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU       4   ()
  1  PHOT          1 BinTableHDU     94   134R x 32C   [K, K, 24A, 57A, D, D, D, D, D, K, 196A, L, 5D, 5D, 5D, 5D, 5D, 5D, 5D, 5D, 5D, 5D, 5D, 5D, 5D, 5D, 5D, 5D, 5D, 5D, 5D, 5D]

In [24]:

table = Table.read("deGraaff2025_lrds_withdups_blackbody_eline_fits.fits")

data = {}

for col in table.colnames:
    arr = np.array(table[col])

    if arr.ndim == 1:
        data[col] = arr
    else:
        for i in range(arr.shape[1]):
            data[f"{col}_{i}"] = arr[:, i]

df = pd.DataFrame(data)

df.head()

,pid,srcid,root,file,ra,dec,zspec,f444w_aper0.1,mu,Ndup,...,LOI_8446_0,LOI_8446_1,LOI_8446_2,LOI_8446_3,LOI_8446_4,logLOI_8446_0,logLOI_8446_1,logLOI_8446_2,logLOI_8446_3,logLOI_8446_4
0,6368,43711,b'capers-cos07-v4',b'capers-cos07-v4_prism-clear_6368_43711.spec....,150.102626,2.249597,4.420440,181.549630,1.0,0,...,1.204418e+41,1.329451e+41,1.518157e+41,1.713626e+41,1.848623e+41,41.080777,41.123672,41.181317,41.233916,41.266848
1,6368,119334,b'capers-cos10-v4',b'capers-cos10-v4_prism-clear_6368_119334.spec...,150.136253,2.308030,9.294025,55.454540,1.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6368,30440,b'capers-cos10-v4',b'capers-cos10-v4_prism-clear_6368_30440.spec....,150.120910,2.317934,3.504500,158.032135,1.0,0,...,1.215027e+41,1.299733e+41,1.428087e+41,1.560501e+41,1.660314e+41,41.084586,41.113854,41.154755,41.193264,41.220190
3,6368,32659,b'capers-cos10-v4',b'capers-cos10-v4_prism-clear_6368_32659.spec....,150.124025,2.306827,4.442170,48.655941,1.0,0,...,5.702253e+39,1.479514e+40,3.043077e+40,4.748942e+40,5.941310e+40,39.881385,40.192852,40.488408,40.677228,40.774987
4,6368,160387,b'capers-cos13-v4',b'capers-cos13-v4_prism-clear_6368_160387.spec...,150.129404,2.393668,6.380030,20.098543,1.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
print(table.colnames)

['pid', 'srcid', 'root', 'file', 'ra', 'dec', 'zspec', 'f444w_aper0.1', 'mu', 'Ndup', 'dup_filenames', 'use_dG25', 'lambda_v', 'beta_UV', 'M_UV', 'break_strength', 'beta_MBB', 'Teff', 'peak_wave', 'logL_MBB', 'logL_5100', 'L5100_LMBB', 'Ha_total_ew', 'Hb_total_ew', 'Balmer_dec_total', 'LHa_total', 'logLHa_total', 'OIII_5007_ew', 'LOIII_5007', 'logLOIII_5007', 'LOI_8446', 'logLOI_8446']

In [22]:
list(df.columns)

['pid',
 'srcid',
 'root',
 'file',
 'ra',
 'dec',
 'zspec',
 'f444w_aper0.1',
 'mu',
 'Ndup',
 'dup_filenames_0',
 'dup_filenames_1',
 'dup_filenames_2',
 'dup_filenames_3',
 'use_dG25',
 'lambda_v_0',
 'lambda_v_1',
 'lambda_v_2',
 'lambda_v_3',
 'lambda_v_4',
 'beta_UV_0',
 'beta_UV_1',
 'beta_UV_2',
 'beta_UV_3',
 'beta_UV_4',
 'M_UV_0',
 'M_UV_1',
 'M_UV_2',
 'M_UV_3',
 'M_UV_4',
 'break_strength_0',
 'break_strength_1',
 'break_strength_2',
 'break_strength_3',
 'break_strength_4',
 'beta_MBB_0',
 'beta_MBB_1',
 'beta_MBB_2',
 'beta_MBB_3',
 'beta_MBB_4',
 'Teff_0',
 'Teff_1',
 'Teff_2',
 'Teff_3',
 'Teff_4',
 'peak_wave_0',
 'peak_wave_1',
 'peak_wave_2',
 'peak_wave_3',
 'peak_wave_4',
 'logL_MBB_0',
 'logL_MBB_1',
 'logL_MBB_2',
 'logL_MBB_3',
 'logL_MBB_4',
 'logL_5100_0',
 'logL_5100_1',
 'logL_5100_2',
 'logL_5100_3',
 'logL_5100_4',
 'L5100_LMBB_0',
 'L5100_LMBB_1',
 'L5100_LMBB_2',
 'L5100_LMBB_3',
 'L5100_LMBB_4',
 'Ha_total_ew_0',
 'Ha_total_ew_1',
 'Ha_total_ew_2',
 'Ha_total_ew_3',
 'Ha_total_ew_4',
 'Hb_total_ew_0',
 'Hb_total_ew_1',
 'Hb_total_ew_2',
 'Hb_total_ew_3',
 'Hb_total_ew_4',
 'Balmer_dec_total_0',
 'Balmer_dec_total_1',
 'Balmer_dec_total_2',
 'Balmer_dec_total_3',
 'Balmer_dec_total_4',
 'LHa_total_0',
 'LHa_total_1',
 'LHa_total_2',
 'LHa_total_3',
 'LHa_total_4',
 'logLHa_total_0',
 'logLHa_total_1',
 'logLHa_total_2',
 'logLHa_total_3',
 'logLHa_total_4',
 'OIII_5007_ew_0',
 'OIII_5007_ew_1',
 'OIII_5007_ew_2',
 'OIII_5007_ew_3',
 'OIII_5007_ew_4',
 'LOIII_5007_0',
 'LOIII_5007_1',
 'LOIII_5007_2',
 'LOIII_5007_3',
 'LOIII_5007_4',
 'logLOIII_5007_0',
 'logLOIII_5007_1',
 'logLOIII_5007_2',
 'logLOIII_5007_3',
 'logLOIII_5007_4',
 'LOI_8446_0',
 'LOI_8446_1',
 'LOI_8446_2',
 'LOI_8446_3',
 'LOI_8446_4',
 'logLOI_8446_0',
 'logLOI_8446_1',
 'logLOI_8446_2',
 'logLOI_8446_3',
 'logLOI_8446_4']

In [25]:
## criar uma tabela apenas com colunas de interesse

colunas_de_interesse = ['pid', 'srcid', 'root', 'file', 'ra', 'dec', 'zspec',
                     'Balmer_dec_total_0', 'Balmer_dec_total_1', 'Balmer_dec_total_2','Balmer_dec_total_3','Balmer_dec_total_4',
                     'LHa_total_0','LHa_total_1','LHa_total_2','LHa_total_3','LHa_total_4',   
                     'LOIII_5007_0','LOIII_5007_1','LOIII_5007_2','LOIII_5007_3','LOIII_5007_4',
]

df_subset = df[colunas_de_interesse].copy()
df_subset

,pid,srcid,root,file,ra,dec,zspec,Balmer_dec_total_0,Balmer_dec_total_1,Balmer_dec_total_2,...,LHa_total_0,LHa_total_1,LHa_total_2,LHa_total_3,LHa_total_4,LOIII_5007_0,LOIII_5007_1,LOIII_5007_2,LOIII_5007_3,LOIII_5007_4
0,6368,43711,b'capers-cos07-v4',b'capers-cos07-v4_prism-clear_6368_43711.spec....,150.102626,2.249597,4.420440,7.660733,7.854381,8.131770,...,5.668301e+42,5.704230e+42,5.758590e+42,5.815786e+42,5.851865e+42,4.000264e+42,4.019672e+42,4.056132e+42,4.091591e+42,4.115029e+42
1,6368,119334,b'capers-cos10-v4',b'capers-cos10-v4_prism-clear_6368_119334.spec...,150.136253,2.308030,9.294025,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.476371e+41,3.258825e+41,4.353137e+41,5.529167e+41,6.301914e+41
2,6368,30440,b'capers-cos10-v4',b'capers-cos10-v4_prism-clear_6368_30440.spec....,150.120910,2.317934,3.504500,7.001882,7.347297,7.822455,...,2.825816e+42,2.852278e+42,2.897211e+42,2.936573e+42,2.959784e+42,1.940875e+42,1.963981e+42,1.990381e+42,2.024247e+42,2.040635e+42
3,6368,32659,b'capers-cos10-v4',b'capers-cos10-v4_prism-clear_6368_32659.spec....,150.124025,2.306827,4.442170,3.211496,3.408269,3.710558,...,7.447690e+41,7.631289e+41,7.921145e+41,8.178681e+41,8.344853e+41,5.652777e+41,5.749388e+41,5.919181e+41,6.089187e+41,6.220264e+41
4,6368,160387,b'capers-cos13-v4',b'capers-cos13-v4_prism-clear_6368_160387.spec...,150.129404,2.393668,6.380030,4.507080,5.072039,6.081922,...,2.314057e+42,2.433602e+42,2.593018e+42,2.725515e+42,2.840988e+42,1.406226e+42,1.450743e+42,1.513514e+42,1.583113e+42,1.627397e+42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,2561,28876,b'uncover-v4',b'uncover-v4_prism-clear_2561_28876.spec.fits',3.569597,-30.373223,7.036244,6.466503,6.709816,7.383194,...,2.859931e+42,2.932661e+42,3.088474e+42,3.276416e+42,3.447768e+42,8.977127e+40,1.052825e+41,1.242843e+41,1.451519e+41,1.577188e+41
130,2561,38108,b'uncover-v4',b'uncover-v4_prism-clear_2561_38108.spec.fits',3.530009,-30.358013,4.968462,9.274564,9.682999,10.321250,...,5.628233e+42,5.667344e+42,5.734779e+42,5.796238e+42,5.830719e+42,1.346203e+42,1.364495e+42,1.397564e+42,1.433028e+42,1.453776e+42
131,2561,4286,b'uncover-v4',b'uncover-v4_prism-clear_2561_4286.spec.fits',3.619201,-30.423270,5.835225,9.631084,9.892641,10.348170,...,9.484496e+42,9.541866e+42,9.637761e+42,9.731975e+42,9.788501e+42,2.497551e+42,2.524050e+42,2.566285e+42,2.606307e+42,2.643634e+42
132,2561,45924,b'uncover-v4',b'uncover-v4_prism-clear_2561_45924.spec.fits',3.584760,-30.343628,4.463361,7.288102,7.483097,7.793566,...,1.113253e+44,1.125604e+44,1.142370e+44,1.158507e+44,1.167201e+44,1.338523e+43,1.365895e+43,1.411858e+43,1.452392e+43,1.479734e+43
133,2561,49702,b'uncover-v4',b'uncover-v4_prism-clear_2561_49702.spec.fits',3.547714,-30.333702,4.866683,5.776415,6.290820,7.124892,...,1.294679e+42,1.312337e+42,1.344190e+42,1.376628e+42,1.403176e+42,4.182669e+41,4.304608e+41,4.536770e+41,4.774447e+41,4.915949e+41

In [32]:
pd.set_option('display.max_columns', 50)
df_subset['LHb_total_0'] = df_subset['LHa_total_0'] / df_subset['Balmer_dec_total_0']
df_subset['LHb_total_1'] = df_subset['LHa_total_1'] / df_subset['Balmer_dec_total_1']
df_subset['LHb_total_2'] = df_subset['LHa_total_2'] / df_subset['Balmer_dec_total_2']
df_subset['LHb_total_3'] = df_subset['LHa_total_3'] / df_subset['Balmer_dec_total_3']
df_subset['LHb_total_4'] = df_subset['LHa_total_4'] / df_subset['Balmer_dec_total_4']
df_subset.head()

,pid,srcid,root,file,ra,dec,zspec,Balmer_dec_total_0,Balmer_dec_total_1,Balmer_dec_total_2,Balmer_dec_total_3,Balmer_dec_total_4,LHa_total_0,LHa_total_1,LHa_total_2,LHa_total_3,LHa_total_4,LOIII_5007_0,LOIII_5007_1,LOIII_5007_2,LOIII_5007_3,LOIII_5007_4,LHb_total_0,LHb_total_1,LHb_total_2,LHb_total_3,LHb_total_4
0,6368,43711,b'capers-cos07-v4',b'capers-cos07-v4_prism-clear_6368_43711.spec....,150.102626,2.249597,4.420440,7.660733,7.854381,8.131770,8.423320,8.642884,5.668301e+42,5.704230e+42,5.758590e+42,5.815786e+42,5.851865e+42,4.000264e+42,4.019672e+42,4.056132e+42,4.091591e+42,4.115029e+42,7.399162e+41,7.262481e+41,7.081596e+41,6.904386e+41,6.770732e+41
1,6368,119334,b'capers-cos10-v4',b'capers-cos10-v4_prism-clear_6368_119334.spec...,150.136253,2.308030,9.294025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.476371e+41,3.258825e+41,4.353137e+41,5.529167e+41,6.301914e+41,NaN,NaN,NaN,NaN,NaN
2,6368,30440,b'capers-cos10-v4',b'capers-cos10-v4_prism-clear_6368_30440.spec....,150.120910,2.317934,3.504500,7.001882,7.347297,7.822455,8.356926,8.722397,2.825816e+42,2.852278e+42,2.897211e+42,2.936573e+42,2.959784e+42,1.940875e+42,1.963981e+42,1.990381e+42,2.024247e+42,2.040635e+42,4.035794e+41,3.882078e+41,3.703710e+41,3.513939e+41,3.393315e+41
3,6368,32659,b'capers-cos10-v4',b'capers-cos10-v4_prism-clear_6368_32659.spec....,150.124025,2.306827,4.442170,3.211496,3.408269,3.710558,4.025521,4.282236,7.447690e+41,7.631289e+41,7.921145e+41,8.178681e+41,8.344853e+41,5.652777e+41,5.749388e+41,5.919181e+41,6.089187e+41,6.220264e+41,2.319072e+41,2.239051e+41,2.134758e+41,2.031707e+41,1.948714e+41
4,6368,160387,b'capers-cos13-v4',b'capers-cos13-v4_prism-clear_6368_160387.spec...,150.129404,2.393668,6.380030,4.507080,5.072039,6.081922,7.440252,8.931528,2.314057e+42,2.433602e+42,2.593018e+42,2.725515e+42,2.840988e+42,1.406226e+42,1.450743e+42,1.513514e+42,1.583113e+42,1.627397e+42,5.134270e+41,4.798073e+41,4.263485e+41,3.663203e+41,3.180853e+41